### ISSUE TITLE
Switch claim reconcilers from HasDirectClassReferenceKind to IsManagedKind predicate

### ISSUE THREAD

**Issue by negz** [crossplaneio/stack-aws#17]
### What happened?
HasDirectClassReferenceKind does not support static provisioning. crossplane-runtime has been updated with a fix, but this stack must be updated. See crossplaneio/crossplane-runtime#28 for details.

**Comment by negz** [comment]
https://github.com/crossplaneio/crossplane-runtime/issues/33

**Comment by hasheddan** [comment]
Closing this in favor of #16 and opening an issue of its kind on `stack-gcp`, which is where I believe this was intended to be opened.
